import Head from 'next/head'
import Image from 'next/image'
import { About } from '../components/About'
import { Main } from '../components/Main'
import { Navbar } from '../components/Navbar'
import { ToolKits } from '../components/ToolKits'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Main />
      <About />
      <ToolKits />
    </div>
  )
}
